/* eslint-disable import/prefer-default-export */

export const CALL_API = 'CALL_API';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const FIXTURES_REQUEST = 'FIXTURES_REQUEST';
export const FIXTURES_SUCCESS = 'FIXTURES_SUCCESS';
export const FIXTURES_FAILURE = 'FIXTURES_FAILURE';
export const RESULTS_REQUEST = 'RESULTS_REQUEST';
export const RESULTS_SUCCESS = 'RESULTS_SUCCESS';
export const RESULTS_FAILURE = 'RESULTS_FAILURE';
export const STREAM_REQUEST = 'STREAM_REQUEST';
export const STREAM_SUCCESS = 'STREAM_SUCCESS';
export const STREAM_FAILURE = 'STREAM_FAILURE';
export const SET_SHEET = 'SET_SHEET';
export const SET_STREAM = 'SET_STREAM';
export const VERIFY_AUTH_TOKEN_REQUEST = 'VERIFY_AUTH_TOKEN_REQUEST';
export const VERIFY_AUTH_TOKEN_SUCCESS = 'VERIFY_AUTH_TOKEN_SUCCESS';
export const VERIFY_AUTH_TOKEN_FAILURE = 'VERIFY_AUTH_TOKEN_FAILURE';
